spring:
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://127.0.0.1:3306/data_lake_platform?useUnicode=true&characterEncoding=utf8&connectionTimeZone=Asia/Shanghai&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jackson:
    time-zone: Asia/Shanghai

app:
  storage:
    root: ${APP_STORAGE_ROOT:../storage}
  task:
    poll-delay-ms: ${APP_TASK_POLL_DELAY_MS:15000}
